Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select  **Restart** and **Clear All Outputs**, then select **Run All**).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = "MARISSA WANG"
COLLABORATORS = ""

---

# Problem Set 6 
### This is a problem set.  You can work on it with the help of your classmates, Google, or ask me any questions you would like. 
### This problem set is take home.   

In [2]:
import numpy as np
from numpy import random 
rng = random.default_rng(seed = 121)
from sound import pop_scales, make_tone, play_sound

1. Write a function **play_scale** that makes and plays the **first five notes** composing one octave in either ascending or descending order. 

I have imported all the functions in sound.py so you can call them.  If you are not able to, its because sound.py is not in the same folder as this assignment.  

The function `pop_scales()` in the module `sound` returns a dictionary with all the frequencies. You can get a list of all the frequencies in the first octave using the keyword 'frequencies' 

The first note A has a frequency of 440 in the first octave. In the second octave at 880, and all the other frequencies also double. The third octave starts at double that frequency or 1760 (4*440), and all the other frequencies are multiplied by 4.  So for any note we can get the equivalent frequency at any octave using

    frequency = frequency*2**(n_octave-1)


The function **play_scale** should have four input arguments, one is the octave (**n_octave**), the second is the **duration** of each note, and the third is an optional **volume** which defaults to 0.05, and the fourth is an optional order which is a string which is either 'ascend' or 'descend', and defaults to 'ascend'. If an invalid order is given it should not play anything and should print out "Invalid Order"
 

In [3]:

# YOUR CODE HERE


def play_scale(n_octave, duration, volume=0.05, order='ascend'):
    if order != 'ascend' and order != 'descend':
        print("Invalid Order")
        return

    notes = pop_scales()
    asc_notes = notes['frequencies'][0:5]

    asc_notes_octave = asc_notes*2**(n_octave-1)

    if order == 'descend':
        asc_notes_octave = np.flip(asc_notes_octave)

    print(asc_notes_octave)

    for freq in asc_notes_octave:
        tone = make_tone(freq, duration)   # create sine wave
        play_sound(tone, volume)           # play through speakers


# test
play_scale(2, 0.5, order='descend')

[1108 1046  988  932  880]


In [4]:
#should play ascending order 2nd octave
play_scale(2,0.5)


[ 880  932  988 1046 1108]


In [5]:
#should play descending order 1st octave
play_scale(1,0.5,order='descend')

[554 523 494 466 440]


In [6]:
#should play descending order louder volume 
play_scale(2,0.5,volume = 0.15,order='descend')

[1108 1046  988  932  880]


In [7]:
#should not play anything and should print "Invalid Order"
play_scale(2,0.5,order = 'x')

Invalid Order


2. Make a function **random_scale** which randomly plays an ascending or descending scale in a random octave chosen from the first, second or 3rd octave.  

- You should make use of **play_scale** that you created in problem 1.  

- **random_scale** should get as input arguments the **duration**, and an optional parameters for volume which defaults to 0.05.

- It should choose **n_octave** randomly from 1,2,3.  

- The function should play the scale and return a string with the type of scale of played, 'ascend' or 'descend'

- The function should also return which octave was played

Hint: use the random number generator `rng` to randomly select the type of scale and octave to play

In [8]:
# YOUR CODE HERE

def random_scale(duration, volume=0.05):
    octave = rng.integers(1,4)
    order = rng.choice(['ascend','descend'])
    play_scale(octave, duration, volume, order)
    return order, octave

# test
order, octave = random_scale(0.5,0.2)
print(order, octave)


[554 523 494 466 440]


descend 1


In [9]:
rng = random.default_rng(seed = 1211)
order, n_oct = random_scale(0.5,0.2)
print(n_oct)
assert n_oct in [1,2,3]
assert n_oct == 2
assert order == 'descend'

[1760 1864 1976 2092 2216]


3


AssertionError: 

3. Copy and paste your function from Problem Set 5, **get_response** that queries the subject with a prompt and checks if the response is among the correct keys. They should be prompted to respond again if they type any other key. You may use my function from the answer key.   

In [10]:
# YOUR CODE HERE

def get_response(prompt, validresponses):
    while True:
        response = input(prompt)
        for r in validresponses:
            if response == r:
                print(response)
                return response
        print("Invalid Response, Try Again")

4. Write a function called **trial** that uses **random_scale** and **get_response** to play a random scale, then ask for a response of a for ascending and d for descending.

The subject should response with the key `a` for ascending and `d` for descending.  A good prompt might be

        'Respond a for ascending and d for descending: '

The function should evaluate if the response is correct or incorrect and create a variable **accuracy** which is 1 if they get it right and 0 if they get it wrong.

The function should return **accuracy**, **response**, and **order**

The input arguments for trial are **duration** and **volume**.  **volume** should have a default value of 0.05.   

In [11]:
# YOUR CODE HERE

def trial(duration, volume=0.05):
    order, _ = random_scale(duration, volume)
    response = get_response('Respond \'a\' for ascending and \'d\' for descending: ', ['a','d'])

    if (order == 'ascend' and response == 'a') or (order == 'descend' and response == 'd'):
        accuracy = 1
    else:
        accuracy = 0
    
    return accuracy, response, order

In [12]:
accuracy, response, order = trial(0.5)
print(accuracy)

[1108 1046  988  932  880]


StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.