Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select  **Restart** and **Clear All Outputs**, then select **Run All**).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = "Gianna Matreaux"
COLLABORATORS = "Sakomoto"

---

# **Problem Set 1**:  List, Arrays, and Indexing Methods

### This is a problem set.  You can work on it with the help of your classmates, Google, or ask me any questions you would like. 
### There are some new methods introduced in the problem set. 
### I encourage discussion during these problem sets.   
### The problem set is due at 2:50 pm.   
### However, you may continue to work on problems you dont finish, or you want to correct up to Wednesday. You will get 1/2 credit for that additional work.   
### VERY IMPORTANT
### In order for automatic grading and validation to work, it is very important that you make use of the exact variable names specified in the problem statement.
### I will always place these variable names that must be used for automatic grading in **bold**

In [2]:
# your going to need numpy to do this assignment 
import numpy as np 
#frankly, in this class, you will always need numpy.  

1. Create a list called **food** with the following elements 'onion', 'egg', 'bacon', 'tomato', 'ham', 'cheese'. 

In [3]:
# YOUR CODE HERE
food = [ 'onion', 'egg', 'bacon', 'tomato', 'ham', 'cheese']
print(food)

['onion', 'egg', 'bacon', 'tomato', 'ham', 'cheese']


In [4]:
assert len(food)== 6

2. Use *indexing* into the list **food** to make a new list **meat** containing only 'bacon' and 'ham'. Again, using indexing, make a list **veggie** containing 'tomato' and 'onion' in that order. 

In [5]:
# YOUR CODE HERE
meat = food[2:5:2]
print(meat)
veggie = food[3], food[0]
print(veggie)

['bacon', 'ham']
('tomato', 'onion')


In [6]:
assert meat[0] == 'bacon'
assert len(meat) == 2

In [7]:
assert veggie[0] == 'tomato'
assert len(veggie) == 2

3. Create a numpy array called **numbers** containing the numbers 6,24,13,16,8,10,21 in that order. Create an array called **skip1** that starts at element with index 0 and takes every other element of the array **numbers**, by using the `start:stop:step` syntax to index into the array.

In [8]:
# YOUR CODE HERE
numbers = np.array([6,24,13,16,8,10,21])
print(numbers)
skip1 = numbers[0:7:2]
print(skip1)

[ 6 24 13 16  8 10 21]
[ 6 13  8 21]


In [9]:
assert len(numbers) == 7

In [10]:
assert len(skip1) == 4
assert skip1[-1] == 21
assert skip1[1] == 13

4. Make a numpy array called **z** using the numpy function `linspace`, containing values from -100 to 100, including -100 and 100, in steps of 10.  

In [11]:
# YOUR CODE HERE
z = np.linspace(-100,100,21)
print(z)

[-100.  -90.  -80.  -70.  -60.  -50.  -40.  -30.  -20.  -10.    0.   10.
   20.   30.   40.   50.   60.   70.   80.   90.  100.]


In [12]:
assert np.all(np.diff(z) == 10)
### BEGIN HIDDEN TESTS
assert np.size(z) == 21
### END HIDDEN TESTS

5. Create a numpy array **x** with all the odd numbers less than 20 using the numpy function `arange`.  

In [13]:
# YOUR CODE HERE]
x = np.arange(1,20,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [14]:
assert ~np.any(x%2 == 0)

6. Create an array **power** than has all of the powers of 2 from $2^1$ to $2^8$.  There are a number of ways you could tackle this problem and I will accept any of them as long as you produce the array by calculating the powers using python code. 

In [15]:
# YOUR CODE HERE
power = 2**np.arange(1,9)
print(power)

[  2   4   8  16  32  64 128 256]


In [16]:
assert len(power) == 8
assert np,max(power) == 2**8
assert np.min(power) == 2